version: '3'

services:

  gogs:
    image: gogs/gogs:latest
    container_name: gogs-server
    volumes:
      - ./data/gogs:/data
    ports:
      - 10022:22
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:16
    container_name: gogs-db
    restart: always
    environment:
      - POSTGRES_USER=refactorian
      - POSTGRES_PASSWORD=refactorian
      - POSTGRES_DB=refactorian
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - default
